package de.pascal.casambibridge.bridge
import android.bluetooth.*
import android.content.Context
import android.os.*
import java.security.MessageDigest
import java.security.interfaces.ECPublicKey
import java.util.UUID
import java.util.concurrent.ConcurrentLinkedQueue
class CasambiBleClient(private val context:Context,private val config:BridgeConfig,private val log:(String)->Unit,private val listener:Listener){interface Listener{fun onConnected();fun onDisconnected();fun onNotify(data:ByteArray);fun onUnitState(id:Int,online:Boolean,on:Boolean,brightness:Int,rawStateHex:String)};private enum class HS{IDLE,WAIT_INITIAL_READ,WAIT_NOTIFY_ENABLED,WAIT_DEVICE_KEY,WAIT_KEY_ACK,WAIT_AUTH};private val handler=Handler(Looper.getMainLooper());private val manager=context.getSystemService(BluetoothManager::class.java);private val commandQueue=ConcurrentLinkedQueue<CasambiCommand>();private var gatt:BluetoothGatt?=null;private var authChar:BluetoothGattCharacteristic?=null;private var txChar2:BluetoothGattCharacteristic?=null;private var txChar3:BluetoothGattCharacteristic?=null;private var state=HS.IDLE;private var nonce=ByteArray(16);private var transportKey:ByteArray?=null;private var encryptor:CasambiEncryptor?=null;private var authenticated=false;private var txPacketId=2;private var opOrigin=1
 fun connect(){close();val a=manager.adapter;if(a==null||!a.isEnabled){log("Bluetooth Adapter nicht aktiv");return};log("Verbinde BLE zu ${config.casambiMac}");gatt=a.getRemoteDevice(config.casambiMac).connectGatt(context,false,callback,BluetoothDevice.TRANSPORT_LE)}
 fun close(){authenticated=false;try{gatt?.disconnect()}catch(_:Throwable){};try{gatt?.close()}catch(_:Throwable){};gatt=null;authChar=null;txChar2=null;txChar3=null;state=HS.IDLE}
 fun submitCommand(command:CasambiCommand){handler.post{if(!authenticated||encryptor==null||gatt==null){commandQueue.clear();commandQueue.add(command);log("Command queued Unit ${command.unitId} state=${command.state ?: "-"} brightness=${command.brightness ?: -1} effective=${command.effectiveBrightness}")}else attemptCasambiTx(command)}}
 private fun scheduleServiceDiscovery(g:BluetoothGatt,delayMs:Long,reason:String){handler.postDelayed({if(gatt!==g)return@postDelayed;if(authChar!=null)return@postDelayed;try{log("Service Discovery Versuch reason=$reason delay=${delayMs}ms");val started=g.discoverServices();log("discoverServices()=$started reason=$reason")}catch(t:Throwable){log("discoverServices Fehler reason=$reason: ${t.message}")}},delayMs)}
 private val callback=object:BluetoothGattCallback(){override fun onConnectionStateChange(g:BluetoothGatt,status:Int,newState:Int){handler.post{if(newState==BluetoothProfile.STATE_CONNECTED&&status==BluetoothGatt.GATT_SUCCESS){log("GATT verbunden, request MTU + Discovery-Watchdog");listener.onConnected();try{g.requestConnectionPriority(BluetoothGatt.CONNECTION_PRIORITY_HIGH)}catch(_:Throwable){};try{g.requestMtu(517)}catch(_:Throwable){};scheduleServiceDiscovery(g,150,"connect-fast");scheduleServiceDiscovery(g,800,"connect-normal");scheduleServiceDiscovery(g,1800,"connect-watchdog")}else if(newState==BluetoothProfile.STATE_DISCONNECTED){log("GATT getrennt status=$status");close();listener.onDisconnected()}}};override fun onMtuChanged(g:BluetoothGatt,mtu:Int,status:Int){log("MTU mtu=$mtu status=$status");scheduleServiceDiscovery(g,80,"mtu-changed")};override fun onServicesDiscovered(g:BluetoothGatt,status:Int){handler.post{log("Services discovered status=$status count=${g.services.size}");if(status!=BluetoothGatt.GATT_SUCCESS)return@post;val chars=g.services.flatMap{it.characteristics};chars.forEach{log("Char ${it.uuid} props=${it.properties}")};authChar=chars.firstOrNull{it.uuid==AUTH_UUID};txChar2=chars.firstOrNull{it.uuid==TX2_UUID};txChar3=chars.firstOrNull{it.uuid==TX3_UUID};if(authChar==null){log("CASA_AUTH_CHAR_UUID nicht gefunden");return@post};log("TX candidates: 0002=${txChar2!=null} 0003=${txChar3!=null}");log("Lese initiale Auth Characteristic vor Notify");state=HS.WAIT_INITIAL_READ;g.readCharacteristic(authChar)}};override fun onCharacteristicRead(g:BluetoothGatt,c:BluetoothGattCharacteristic,status:Int){handler.post{if(c.uuid==AUTH_UUID){val d=c.value?:ByteArray(0);log("Initial Auth Read status=$status bytes=${d.size}");if(status==BluetoothGatt.GATT_SUCCESS&&parseInitialAuth(d))enableAuthNotify(g,c)}}};override fun onDescriptorWrite(g:BluetoothGatt,d:BluetoothGattDescriptor,status:Int){handler.post{log("Notify Descriptor write status=$status state=$state");if(status==BluetoothGatt.GATT_SUCCESS&&state==HS.WAIT_NOTIFY_ENABLED){state=HS.WAIT_DEVICE_KEY;log("Warte auf Device Public Key Notify 0x02 oder 65 Byte")}else if(status==BluetoothGatt.GATT_SUCCESS)log("Spaeter Descriptor-Write wird ignoriert, State bleibt $state")}};override fun onCharacteristicWrite(g:BluetoothGatt,c:BluetoothGattCharacteristic,status:Int){handler.post{log("GATT write ${c.uuid} status=$status")}};override fun onCharacteristicChanged(g:BluetoothGatt,c:BluetoothGattCharacteristic){val d=c.value?:ByteArray(0);handler.post{log("Notify ${d.size} bytes: ${HexUtil.bytesToHex(d)}");handleNotify(d);listener.onNotify(d)}}}
 private fun enableAuthNotify(g:BluetoothGatt,c:BluetoothGattCharacteristic){log("Aktiviere Notify ${c.uuid} nach Initial Auth");state=HS.WAIT_NOTIFY_ENABLED;g.setCharacteristicNotification(c,true);val desc=c.getDescriptor(CCCD_UUID);if(desc!=null){desc.value=BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE;g.writeDescriptor(desc)}else state=HS.WAIT_DEVICE_KEY}
 private fun parseInitialAuth(d:ByteArray):Boolean{if(d.size<23||d[0]!=1.toByte()){log("Initial Auth unerwartet: ${HexUtil.bytesToHex(d)}");return false};nonce=d.copyOfRange(7,23);log("Initial Auth OK proto=${d[1].toInt()and 255} mtu=${d[2].toInt()and 255} unit=${((d[3].toInt()and 255)shl 8)or(d[4].toInt()and 255)} flags=${((d[5].toInt()and 255)shl 8)or(d[6].toInt()and 255)} nonce=${HexUtil.bytesToHex(nonce)}");return true}
 private fun handleNotify(d:ByteArray){if(d.isEmpty())return;when(state){HS.WAIT_NOTIFY_ENABLED->if(d.size>=65){log("65-Byte Notify waehrend WAIT_NOTIFY_ENABLED erkannt, teste als Device Public Key");handleDevicePublicKey(d)}else log("Notify in State $state ignoriert: ${HexUtil.bytesToHex(d)}");HS.WAIT_DEVICE_KEY->if(d[0]==2.toByte()||d.size>=65)handleDevicePublicKey(d)else if(d[0]==3.toByte()&&transportKey!=null){log("Key ACK 0x03 kam waehrend WAIT_DEVICE_KEY, behandle als ACK");handleKeyAck(d)}else log("Ignoriere Notify vor Device Public Key: first=0x${String.format("%02X",d[0])}");HS.WAIT_KEY_ACK->if(d[0]==3.toByte())handleKeyAck(d)else log("Warte auf Key ACK, bekam ${HexUtil.bytesToHex(d)}");HS.WAIT_AUTH->handleAuthResponse(d);HS.IDLE->handleEstablishedPacket(d);HS.WAIT_INITIAL_READ->log("Notify in State $state ignoriert")}}
 private fun handleDevicePublicKey(d:ByteArray){val typed=d.size>=65&&d[0]==2.toByte();val x:ByteArray;val y:ByteArray;val fmt:String;if(typed){fmt="typed-0x02";x=d.copyOfRange(1,33);y=d.copyOfRange(33,65)}else if(d.size==65){fmt="typeless-65";x=d.copyOfRange(0,32);y=d.copyOfRange(32,64)}else{log("Device Public Key Paket unerwartete Laenge=${d.size}");return};try{val kp=CasambiEcdh.generateKeyPair();val pub=kp.public as ECPublicKey;val dev=CasambiEcdh.publicKeyFromLittleEndian(x,y,pub.params);transportKey=CasambiEcdh.transportKey(kp,dev);encryptor=CasambiEncryptor(transportKey!!);log("Device Public Key empfangen format=$fmt, Transport Key berechnet");val cx=CasambiEcdh.publicKeyCoordinateLittleEndian(pub,true);val cy=CasambiEcdh.publicKeyCoordinateLittleEndian(pub,false);val resp=if(typed)ByteArray(66).also{it[0]=2;System.arraycopy(cx,0,it,1,32);System.arraycopy(cy,0,it,33,32);it[65]=1}else ByteArray(65).also{System.arraycopy(cx,0,it,0,32);System.arraycopy(cy,0,it,32,32);it[64]=1};writeChar(authChar,resp);state=HS.WAIT_KEY_ACK;log("Client Public Key gesendet format=$fmt bytes=${resp.size}; warte auf ACK 0x03")}catch(t:Throwable){log("Device Public Key konnte nicht verarbeitet werden: ${t.javaClass.simpleName}: ${t.message}")}}
 private fun handleKeyAck(d:ByteArray){if(d.size==1&&d[0]==3.toByte()){log("Key Exchange ACK erhalten");sendAuthPacket()}else log("Unerwarteter Key ACK: ${HexUtil.bytesToHex(d)}")}
 private fun sendAuthPacket(){val key=try{HexUtil.hexToBytes(config.casambiKeyHex)}catch(t:Throwable){log("Key HEX ungueltig: ${t.message}");return};val tr=transportKey?:return;val dg=MessageDigest.getInstance("SHA-256").digest(key+nonce+tr);val p=ByteArray(38);p[0]=1;p[4]=4;p[5]=(config.casambiKeyId and 255).toByte();System.arraycopy(dg,0,p,6,32);val enc=encryptPacket(p,1)?:return;writeChar(authChar,enc);state=HS.WAIT_AUTH;log("Auth Packet gesendet keyId=${config.casambiKeyId}")}
 private fun handleAuthResponse(d:ByteArray){val pt=encryptor?.decryptAndVerify(d,d.copyOfRange(0,4)+nonce.copyOfRange(4,16));if(pt==null){log("Auth Response Signatur ungueltig");return};authenticated=true;state=HS.IDLE;log("Authentication successful payload=${HexUtil.bytesToHex(pt)}");processQueuedCommands()}
 private fun handleEstablishedPacket(d:ByteArray){val pt=encryptor?.decryptAndVerify(d,d.copyOfRange(0,4)+nonce.copyOfRange(4,16));if(pt==null){log("Encrypted Packet ungueltig oder noch nicht authentifiziert");return};val type=pt.firstOrNull()?.toInt()?.and(255)?:-1;log("Decrypted Packet type=$type len=${pt.size} payload=${HexUtil.bytesToHex(pt)}");if(type==6)parseUnitStates(pt.copyOfRange(1,pt.size))}
 private fun parseUnitStates(data:ByteArray){var pos=0;var count=0;try{while(pos<=data.size-4){val id=data[pos].toInt()and 255;val flags=data[pos+1].toInt()and 255;val stateLen=((data[pos+2].toInt() ushr 4)and 15)+1;val prio=data[pos+2].toInt()and 15;pos+=3;val online=(flags and 2)!=0;val on=(flags and 1)!=0;if((flags and 4)!=0)pos++;if((flags and 8)!=0)pos++;if((flags and 16)!=0)pos++;if(pos+stateLen>data.size)return;val st=data.copyOfRange(pos,pos+stateLen);pos+=stateLen;pos+=(flags ushr 6)and 3;val b=st.firstOrNull()?.toInt()?.and(255)?:0;val raw=HexUtil.bytesToHex(st);log("UnitState id=$id online=$online on=$on prio=$prio stateLen=$stateLen state=$raw brightness=$b");listener.onUnitState(id,online,on,b,raw);count++};log("UnitState parsing fertig count=$count")}catch(t:Throwable){log("UnitState parse error ${t.javaClass.simpleName}: ${t.message}")}}
 private fun processQueuedCommands(){var cmd=commandQueue.poll();while(cmd!=null){log("Processing queued command Unit ${cmd.unitId} effective=${cmd.effectiveBrightness}");attemptCasambiTx(cmd);cmd=commandQueue.poll()}}
 private fun attemptCasambiTx(command:CasambiCommand){val brightness=command.effectiveBrightness.coerceIn(0,255);val packetId=txPacketId++;val origin=opOrigin++ and 0xFFFF;val targetCode=((command.unitId and 0xFF)shl 8)or(command.targetType and 0xFF);val levelPayload=if(command.targetType==1&&command.state.equals("ON",true)&&command.brightness==null)byteArrayOf(0xFF.toByte(),0x05)else byteArrayOf(brightness.toByte());val op=prepareOperationPacket(1,targetCode,origin,levelPayload);val targetName=when(command.targetType){1->"Unit";2->"Group";4->"Scene";else->"Target"};log("Casambi TX Operation $targetName=${command.unitId} label=${command.label ?: "-"} state=${command.state ?: "-"} brightness=$brightness packetId=$packetId origin=$origin target=0x${String.format("%04X",targetCode)}");log("TX Operation payload=${HexUtil.bytesToHex(levelPayload)} opPacket=${HexUtil.bytesToHex(op)}");val header=byteArrayOf((packetId and 255).toByte(),((packetId shr 8)and 255).toByte(),((packetId shr 16)and 255).toByte(),0x00);val frame=header+byteArrayOf(0x07)+op;log("TX Frame header=${HexUtil.bytesToHex(header)} type=07 operation=${HexUtil.bytesToHex(op)} frame=${HexUtil.bytesToHex(frame)}");val encrypted=encryptPacket(frame,packetId);if(encrypted==null){log("TX fehlgeschlagen: Encryptor nicht bereit");return};val target=authChar?:txChar2?:txChar3;log("TX Encrypted operation=${HexUtil.bytesToHex(encrypted)} writeUuid=${target?.uuid} mode=counter-07-operation-on-0001");writeChar(target,encrypted)}
 private fun prepareOperationPacket(op:Int,target:Int,origin:Int,payload:ByteArray):ByteArray{val flags=((5 and 15)shl 11)or payload.size;return byteArrayOf(((flags shr 8)and 255).toByte(),(flags and 255).toByte(),(op and 255).toByte(),((origin shr 8)and 255).toByte(),(origin and 255).toByte(),((target shr 8)and 255).toByte(),(target and 255).toByte(),0x00,0x00)+payload}
 private fun encryptPacket(packet:ByteArray,id:Int):ByteArray?{val e=encryptor?:return null;val ib=byteArrayOf((id and 255).toByte(),((id shr 8)and 255).toByte(),((id shr 16)and 255).toByte(),((id shr 24)and 255).toByte());return e.encryptThenMac(packet,nonce.copyOfRange(0,4)+ib+nonce.copyOfRange(8,16))}
 private fun writeChar(ch:BluetoothGattCharacteristic?,data:ByteArray){val g=gatt?:run{log("GATT write nicht moeglich: gatt=null");return};val c=ch?:run{log("GATT write nicht moeglich: characteristic=null");return};c.value=data;c.writeType=BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT;g.writeCharacteristic(c)}
 companion object{private val CCCD_UUID:UUID=UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");private val AUTH_UUID:UUID=UUID.fromString("c9ffde48-ca5a-0001-ab83-8f519b482f77");private val TX2_UUID:UUID=UUID.fromString("c9ffde48-ca5a-0002-ab83-8f519b482f77");private val TX3_UUID:UUID=UUID.fromString("c9ffde48-ca5a-0003-ab83-8f519b482f77")}}
