package de.pascal.casambibridge.bridge
import java.math.BigInteger
import java.security.*
import java.security.interfaces.ECPublicKey
import java.security.spec.*
import javax.crypto.*
import javax.crypto.spec.SecretKeySpec
object HexUtil{fun hexToBytes(input:String):ByteArray{val c=input.replace(" ","").replace(":","").trim();require(c.length%2==0);return ByteArray(c.length/2){i->c.substring(i*2,i*2+2).toInt(16).toByte()}};fun bytesToHex(d:ByteArray)=d.joinToString(""){"%02X".format(it)}}
object CasambiEcdh{private fun le(d:ByteArray)=BigInteger(1,d.reversedArray());fun generateKeyPair():KeyPair{val k=KeyPairGenerator.getInstance("EC");k.initialize(ECGenParameterSpec("secp256r1"),SecureRandom());return k.generateKeyPair()};fun publicKeyFromLittleEndian(x:ByteArray,y:ByteArray,p:ECParameterSpec):ECPublicKey=KeyFactory.getInstance("EC").generatePublic(ECPublicKeySpec(ECPoint(le(x),le(y)),p)) as ECPublicKey;fun publicKeyCoordinateLittleEndian(k:ECPublicKey,x:Boolean):ByteArray{val c=if(x)k.w.affineX else k.w.affineY;val be=c.toByteArray().dropWhile{it==0.toByte()}.toByteArray();val pad=ByteArray(32);val cs=maxOf(0,be.size-32);val cl=minOf(32,be.size);System.arraycopy(be,cs,pad,32-cl,cl);return pad.reversedArray()};fun transportKey(kp:KeyPair,dev:ECPublicKey):ByteArray{val ka=KeyAgreement.getInstance("ECDH");ka.init(kp.private);ka.doPhase(dev,true);val dg=MessageDigest.getInstance("SHA-256").digest(ka.generateSecret().reversedArray());return ByteArray(16){i->(dg[i].toInt() xor dg[16+i].toInt()).toByte()}}}
class CasambiEncryptor(private val key:ByteArray){private fun aes(b:ByteArray):ByteArray{val c=Cipher.getInstance("AES/ECB/NoPadding");c.init(Cipher.ENCRYPT_MODE,SecretKeySpec(key,"AES"));return c.doFinal(b)};private fun crypt(d:ByteArray,n:ByteArray):ByteArray{val r=ByteArray(d.size);var off=0;var ctr=0;while(off<d.size){val nn=n.copyOf();nn[12]=(ctr and 255).toByte();nn[13]=((ctr shr 8)and 255).toByte();nn[14]=((ctr shr 16)and 255).toByte();nn[15]=((ctr shr 24)and 255).toByte();val s=aes(nn);val len=minOf(16,d.size-off);for(i in 0 until len)r[off+i]=(d[off+i].toInt() xor s[i].toInt()).toByte();off+=len;ctr++};return r};private fun cmac(d:ByteArray):ByteArray=try{val m=Mac.getInstance("AESCMAC");m.init(SecretKeySpec(key,"AES"));m.doFinal(d)}catch(_:Throwable){cmacFallback(d)};fun encryptThenMac(p:ByteArray,n:ByteArray,hl:Int=4):ByteArray{val e=p.copyOfRange(0,hl)+crypt(p.copyOfRange(hl,p.size),n);return e+cmac(e)};fun decryptAndVerify(p:ByteArray,n:ByteArray,hl:Int=4):ByteArray?{if(p.size<16+hl)return null;val c=p.copyOfRange(0,p.size-16);if(!p.copyOfRange(p.size-16,p.size).contentEquals(cmac(c)))return null;return crypt(c.copyOfRange(hl,c.size),n)};private fun sh(i:ByteArray):ByteArray{val o=ByteArray(i.size);var ca=0;for(x in i.indices.reversed()){val v=i[x].toInt()and 255;o[x]=(((v shl 1)and 255)or ca).toByte();ca=(v ushr 7)and 1};return o};private fun xor(a:ByteArray,b:ByteArray)=ByteArray(16){i->(a[i].toInt() xor b[i].toInt()).toByte()};private fun cmacFallback(m:ByteArray):ByteArray{val l=aes(ByteArray(16));val rb=ByteArray(16).also{it[15]=0x87.toByte()};var k1=sh(l);if((l[0].toInt()and 128)!=0)k1=xor(k1,rb);var k2=sh(k1);if((k1[0].toInt()and 128)!=0)k2=xor(k2,rb);val n=if(m.isEmpty())1 else (m.size+15)/16;val complete=m.isNotEmpty()&&m.size%16==0;val last=ByteArray(16);if(complete){System.arraycopy(m,(n-1)*16,last,0,16);System.arraycopy(xor(last,k1),0,last,0,16)}else{val ll=m.size-(n-1)*16;if(ll>0)System.arraycopy(m,(n-1)*16,last,0,ll);last[ll]=0x80.toByte();System.arraycopy(xor(last,k2),0,last,0,16)};var x=ByteArray(16);for(i in 0 until n-1)x=aes(xor(x,m.copyOfRange(i*16,i*16+16)));return aes(xor(x,last))}}
