package de.pascal.casambibridge.bridge
import android.content.Context
object ConfigStore { private const val PREF="casambi_bridge_config"
 fun load(context:Context):BridgeConfig { val p=context.getSharedPreferences(PREF,Context.MODE_PRIVATE); return BridgeConfig(
  p.getString("casambiMac","7A:1B:1E:FF:63:4A")?:"7A:1B:1E:FF:63:4A", p.getString("casambiNetworkName","")?:"", p.getString("casambiPassword","")?:"", p.getInt("casambiProtocolVersion",11), p.getInt("casambiKeyId",2), p.getString("casambiKeyHex","")?:"",
  p.getString("mqttHost","")?:"", p.getInt("mqttPort",1883), p.getString("mqttUser","")?:"", p.getString("mqttPassword","")?:"", p.getString("baseTopic","casambi_bridge")?:"casambi_bridge", p.getString("discoveryPrefix","homeassistant")?:"homeassistant",
  p.getBoolean("smbDebugEnabled",false), p.getString("smbServer","")?:"", p.getString("smbShare","")?:"", p.getString("smbPath","casambi_debug")?:"casambi_debug", p.getString("smbDomain","")?:"", p.getString("smbUser","")?:"", p.getString("smbPassword","")?:"",
  p.getBoolean("tcpLogEnabled",false), p.getInt("tcpLogPort",5555), p.getBoolean("webInterfaceEnabled",false), p.getInt("webInterfacePort",8080), p.getBoolean("autoApiFetchEnabled",false)) }
 fun save(context:Context,c:BridgeConfig){ context.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().putString("casambiMac",c.casambiMac).putString("casambiNetworkName",c.casambiNetworkName).putString("casambiPassword",c.casambiPassword).putInt("casambiProtocolVersion",c.casambiProtocolVersion).putInt("casambiKeyId",c.casambiKeyId).putString("casambiKeyHex",c.casambiKeyHex).putString("mqttHost",c.mqttHost).putInt("mqttPort",c.mqttPort).putString("mqttUser",c.mqttUser).putString("mqttPassword",c.mqttPassword).putString("baseTopic",c.baseTopic).putString("discoveryPrefix",c.discoveryPrefix).putBoolean("smbDebugEnabled",c.smbDebugEnabled).putString("smbServer",c.smbServer).putString("smbShare",c.smbShare).putString("smbPath",c.smbPath).putString("smbDomain",c.smbDomain).putString("smbUser",c.smbUser).putString("smbPassword",c.smbPassword).putBoolean("tcpLogEnabled",c.tcpLogEnabled).putInt("tcpLogPort",c.tcpLogPort).putBoolean("webInterfaceEnabled",c.webInterfaceEnabled).putInt("webInterfacePort",c.webInterfacePort).putBoolean("autoApiFetchEnabled",c.autoApiFetchEnabled).apply() }
}
