package de.pascal.casambibridge.bridge
import jcifs.smb.*
import org.json.JSONObject
object ConfigBackup { private const val FILE="casambi_bridge_config.json"
 fun exportToSmb(c:BridgeConfig):String{val ctx=DebugExporter.smbContext(c);val dir=DebugExporter.smbDir(c);SmbFile(dir,ctx).use{if(!it.exists())it.mkdirs()};val url=dir+FILE;SmbFileOutputStream(SmbFile(url,ctx),false).use{it.write(toJson(c).toString(2).toByteArray(Charsets.UTF_8))};return url}
 fun restoreFromSmb(c:BridgeConfig):BridgeConfig{val ctx=DebugExporter.smbContext(c);val url=DebugExporter.smbDir(c)+FILE;val text=SmbFileInputStream(SmbFile(url,ctx)).use{it.readBytes().toString(Charsets.UTF_8)};return fromJson(JSONObject(text),c)}
 private fun toJson(c:BridgeConfig)=JSONObject().put("casambiMac",c.casambiMac).put("casambiNetworkName",c.casambiNetworkName).put("casambiPassword",c.casambiPassword).put("casambiProtocolVersion",c.casambiProtocolVersion).put("casambiKeyId",c.casambiKeyId).put("casambiKeyHex",c.casambiKeyHex).put("mqttHost",c.mqttHost).put("mqttPort",c.mqttPort).put("mqttUser",c.mqttUser).put("mqttPassword",c.mqttPassword).put("baseTopic",c.baseTopic).put("discoveryPrefix",c.discoveryPrefix).put("smbDebugEnabled",c.smbDebugEnabled).put("smbServer",c.smbServer).put("smbShare",c.smbShare).put("smbPath",c.smbPath).put("smbDomain",c.smbDomain).put("smbUser",c.smbUser).put("smbPassword",c.smbPassword).put("tcpLogEnabled",c.tcpLogEnabled).put("tcpLogPort",c.tcpLogPort).put("webInterfaceEnabled",c.webInterfaceEnabled).put("webInterfacePort",c.webInterfacePort).put("autoApiFetchEnabled",c.autoApiFetchEnabled)
 private fun fromJson(j:JSONObject,f:BridgeConfig)=BridgeConfig(j.optString("casambiMac",f.casambiMac),j.optString("casambiNetworkName",f.casambiNetworkName),j.optString("casambiPassword",f.casambiPassword),j.optInt("casambiProtocolVersion",f.casambiProtocolVersion),j.optInt("casambiKeyId",f.casambiKeyId),j.optString("casambiKeyHex",f.casambiKeyHex),j.optString("mqttHost",f.mqttHost),j.optInt("mqttPort",f.mqttPort),j.optString("mqttUser",f.mqttUser),j.optString("mqttPassword",f.mqttPassword),j.optString("baseTopic",f.baseTopic),j.optString("discoveryPrefix",f.discoveryPrefix),j.optBoolean("smbDebugEnabled",f.smbDebugEnabled),j.optString("smbServer",f.smbServer),j.optString("smbShare",f.smbShare),j.optString("smbPath",f.smbPath),j.optString("smbDomain",f.smbDomain),j.optString("smbUser",f.smbUser),j.optString("smbPassword",f.smbPassword),j.optBoolean("tcpLogEnabled",f.tcpLogEnabled),j.optInt("tcpLogPort",f.tcpLogPort),j.optBoolean("webInterfaceEnabled",f.webInterfaceEnabled),j.optInt("webInterfacePort",f.webInterfacePort),j.optBoolean("autoApiFetchEnabled",f.autoApiFetchEnabled))
}
